//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P11WebAPI.P11DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MatchTopicMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_MatchTopicMaster()
        {
            this.T_LiveMatchUpdateInfo = new HashSet<T_LiveMatchUpdateInfo>();
        }
    
        public int MatchTopicID { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LiveMatchUpdateInfo> T_LiveMatchUpdateInfo { get; set; }
    }
}
