//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P11WebAPI.P11DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MatchInfoMaters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_MatchInfoMaters()
        {
            this.T_LiveMatchUpdateInfo = new HashSet<T_LiveMatchUpdateInfo>();
            this.T_Match_PlayerMappingTable = new HashSet<T_Match_PlayerMappingTable>();
            this.T_RunningMatchInfo = new HashSet<T_RunningMatchInfo>();
        }
    
        public int MatchID { get; set; }
        public string MatchLocation { get; set; }
        public int Team1 { get; set; }
        public int Team2 { get; set; }
        public System.DateTime MatchDate { get; set; }
        public string Result { get; set; }
        public string TotalOverMatch { get; set; }
        public Nullable<int> LiveWatchingCount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
        public string MatchBanner { get; set; }
        public string FirstAmpire { get; set; }
        public string SecondAmpire { get; set; }
    
        public virtual M_TeamInfoMaster M_TeamInfoMaster { get; set; }
        public virtual M_TeamInfoMaster M_TeamInfoMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LiveMatchUpdateInfo> T_LiveMatchUpdateInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Match_PlayerMappingTable> T_Match_PlayerMappingTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RunningMatchInfo> T_RunningMatchInfo { get; set; }
    }
}
