//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P11WebAPI.P11DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PlayerInfoMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_PlayerInfoMaster()
        {
            this.T_Match_PlayerMappingTable = new HashSet<T_Match_PlayerMappingTable>();
        }
    
        public int PlayerID { get; set; }
        public int TeamID { get; set; }
        public string PlayerName { get; set; }
        public int PlayerTypeID { get; set; }
        public string PlayerSpecialization { get; set; }
        public string Description { get; set; }
        public string PlayerImage { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_PlayerTypeMaster M_PlayerTypeMaster { get; set; }
        public virtual M_TeamInfoMaster M_TeamInfoMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Match_PlayerMappingTable> T_Match_PlayerMappingTable { get; set; }
    }
}
