//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P11WebAPI.P11DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TeamInfoMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_TeamInfoMaster()
        {
            this.M_MatchInfoMaters = new HashSet<M_MatchInfoMaters>();
            this.M_MatchInfoMaters1 = new HashSet<M_MatchInfoMaters>();
            this.M_PlayerInfoMaster = new HashSet<M_PlayerInfoMaster>();
        }
    
        public int TeamID { get; set; }
        public string TeamType { get; set; }
        public string TeamCode { get; set; }
        public string TeamName { get; set; }
        public string TeamLocation { get; set; }
        public string Country { get; set; }
        public string TeamLogo { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_MatchInfoMaters> M_MatchInfoMaters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_MatchInfoMaters> M_MatchInfoMaters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_PlayerInfoMaster> M_PlayerInfoMaster { get; set; }
    }
}
