//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P11WebAPI.P11DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class P11DbEntities1 : DbContext
    {
        public P11DbEntities1()
            : base("name=P11DbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_MatchInfoMaters> M_MatchInfoMaters { get; set; }
        public virtual DbSet<M_MatchTopicMaster> M_MatchTopicMaster { get; set; }
        public virtual DbSet<M_PlayerInfoMaster> M_PlayerInfoMaster { get; set; }
        public virtual DbSet<M_PlayerTypeMaster> M_PlayerTypeMaster { get; set; }
        public virtual DbSet<M_TeamInfoMaster> M_TeamInfoMaster { get; set; }
        public virtual DbSet<T_LiveMatchUpdateInfo> T_LiveMatchUpdateInfo { get; set; }
        public virtual DbSet<T_Match_PlayerMappingTable> T_Match_PlayerMappingTable { get; set; }
        public virtual DbSet<T_RunningMatchInfo> T_RunningMatchInfo { get; set; }
    }
}
